"""
SQLite -> PostgreSQL migration for the VMS known_faces.db

Purpose:
    1. Create the PostgreSQL schema matching the current SQLite database.
    2. Copy all existing rows, IDs, image paths/URLs and face embeddings.
    3. Reset PostgreSQL identity sequences so new records continue after migrated IDs.
    4. Verify row counts and BLOB totals.

Usage (Windows CMD):
    set PGHOST=localhost
    set PGPORT=5432
    set PGDATABASE=vms_test
    set PGUSER=postgres
    set PGPASSWORD=YOUR_POSTGRES_PASSWORD
    python migrate_sqlite_to_postgres.py

Or pass:
    python migrate_sqlite_to_postgres.py --sqlite known_faces.db

The script DOES NOT move or modify image files. It only copies the paths/URLs
stored in SQLite.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sqlite3
import sys
from pathlib import Path
from typing import Any

import psycopg
from psycopg import sql
from dotenv import load_dotenv
load_dotenv()

# -----------------------------
# PostgreSQL schema
# -----------------------------
SCHEMA = """
CREATE TABLE IF NOT EXISTS auth_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role TEXT NOT NULL CHECK (role IN ('admin', 'user')),
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS detection_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detected_at DOUBLE PRECISION NOT NULL,
    known_count BIGINT NOT NULL DEFAULT 0,
    unknown_count BIGINT NOT NULL DEFAULT 0,
    two_wheeler_count BIGINT NOT NULL DEFAULT 0,
    four_wheeler_count BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS detection_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detected_at DOUBLE PRECISION NOT NULL,
    detection_type TEXT NOT NULL,
    person_id TEXT,
    person_name TEXT,
    vehicle_type TEXT,
    vehicle_class TEXT,
    confidence DOUBLE PRECISION,
    gate_name TEXT NOT NULL,
    image_url TEXT,
    created_at DOUBLE PRECISION NOT NULL,
    unknown_count BIGINT,
    camera_id TEXT,
    camera_name TEXT
);

CREATE TABLE IF NOT EXISTS fcm_device_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'user')),
    fcm_token TEXT NOT NULL UNIQUE,
    is_active BIGINT NOT NULL DEFAULT 1,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    last_login_at DOUBLE PRECISION,
    last_logout_at DOUBLE PRECISION,
    CONSTRAINT fk_fcm_account
        FOREIGN KEY (account_id)
        REFERENCES auth_accounts(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS known_embeddings (
    person TEXT PRIMARY KEY,
    embedding BYTEA,
    image_paths TEXT,
    fingerprint TEXT,
    updated_at DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS registered_face_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id TEXT NOT NULL,
    image_number BIGINT NOT NULL,
    image_path TEXT NOT NULL,
    embedding BYTEA NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    CONSTRAINT uq_registered_face_embedding
        UNIQUE (registration_id, image_number)
);

CREATE TABLE IF NOT EXISTS registered_persons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id TEXT NOT NULL UNIQUE,
    storage_key TEXT NOT NULL UNIQUE,
    gate_no TEXT NOT NULL,
    employee_id TEXT UNIQUE,
    employee_name TEXT NOT NULL,
    designation TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_detection_records_camera_id
    ON detection_records(camera_id);

CREATE INDEX IF NOT EXISTS idx_detection_records_detected_at
    ON detection_records(detected_at);
"""

TABLE_COLUMNS = {
    "auth_accounts": [
        "id", "role", "username", "password_hash", "created_at", "updated_at"
    ],
    "detection_events": [
        "id", "detected_at", "known_count", "unknown_count",
        "two_wheeler_count", "four_wheeler_count"
    ],
    "detection_records": [
        "id", "detected_at", "detection_type", "person_id", "person_name",
        "vehicle_type", "vehicle_class", "confidence", "gate_name",
        "image_url", "created_at", "unknown_count", "camera_id", "camera_name"
    ],
    "fcm_device_tokens": [
        "id", "account_id", "role", "fcm_token", "is_active", "created_at",
        "updated_at", "last_login_at", "last_logout_at"
    ],
    "known_embeddings": [
        "person", "embedding", "image_paths", "fingerprint", "updated_at"
    ],
    "registered_face_embeddings": [
        "id", "registration_id", "image_number", "image_path",
        "embedding", "created_at"
    ],
    "registered_persons": [
        "id", "registration_id", "storage_key", "gate_no", "employee_id",
        "employee_name", "designation", "created_at", "updated_at"
    ],
}

IDENTITY_TABLES = {
    "auth_accounts",
    "detection_events",
    "detection_records",
    "fcm_device_tokens",
    "registered_face_embeddings",
    "registered_persons",
}

PRIMARY_KEYS = {
    "auth_accounts": ["id"],
    "detection_events": ["id"],
    "detection_records": ["id"],
    "fcm_device_tokens": ["id"],
    "known_embeddings": ["person"],
    "registered_face_embeddings": ["id"],
    "registered_persons": ["id"],
}


def qident(name: str) -> sql.Identifier:
    return sql.Identifier(name)


def get_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--sqlite",
        default="known_faces.db",
        help="Path to the source SQLite database (default: known_faces.db)",
    )
    parser.add_argument(
        "--truncate",
        action="store_true",
        help="Delete existing rows in the target tables before importing.",
    )
    return parser.parse_args()


def pg_connect():
    # Uses standard PostgreSQL environment variables:
    # PGHOST, PGPORT, PGDATABASE, PGUSER, PGPASSWORD.
    missing = []
    for name in ("PGDATABASE", "PGUSER", "PGPASSWORD"):
        if not os.getenv(name):
            missing.append(name)
    if missing:
        raise RuntimeError(
            "Missing PostgreSQL environment variables: "
            + ", ".join(missing)
            + "\nSet them before running the script."
        )

    return psycopg.connect(
        host=os.getenv("PGHOST", "localhost"),
        port=int(os.getenv("PGPORT", "5432")),
        dbname=os.environ["PGDATABASE"],
        user=os.environ["PGUSER"],
        password=os.environ["PGPASSWORD"],
    )


def sqlite_connect(path: Path) -> sqlite3.Connection:
    if not path.exists():
        raise FileNotFoundError(f"SQLite database not found: {path}")
    con = sqlite3.connect(path)
    con.row_factory = sqlite3.Row
    # Read-only safety: this migration never writes to SQLite.
    con.execute("PRAGMA query_only = ON")
    return con


def get_sqlite_counts(con: sqlite3.Connection) -> dict[str, int]:
    result = {}
    for table in TABLE_COLUMNS:
        row = con.execute(
            f'SELECT COUNT(*) AS c FROM "{table}"'
        ).fetchone()
        result[table] = int(row["c"])
    return result


def get_blob_totals(con: sqlite3.Connection) -> dict[str, int]:
    result = {}
    for table, column in [
        ("known_embeddings", "embedding"),
        ("registered_face_embeddings", "embedding"),
    ]:
        row = con.execute(
            f'SELECT COALESCE(SUM(LENGTH("{column}")), 0) AS n FROM "{table}"'
        ).fetchone()
        result[table] = int(row["n"] or 0)
    return result


def create_schema(pg):
    with pg.cursor() as cur:
        cur.execute(SCHEMA)
    pg.commit()


def truncate_target(pg):
    # Child table first, then parents.
    order = [
        "fcm_device_tokens",
        "registered_face_embeddings",
        "detection_records",
        "detection_events",
        "known_embeddings",
        "registered_persons",
        "auth_accounts",
    ]
    with pg.cursor() as cur:
        for table in order:
            cur.execute(
                sql.SQL("TRUNCATE TABLE {} RESTART IDENTITY CASCADE").format(
                    qident(table)
                )
            )
    pg.commit()


def normalize_value(value: Any):
    # SQLite BLOB -> bytes. psycopg may return memoryview for BYTEA.
    if isinstance(value, memoryview):
        return value.tobytes()
    return value


def copy_table(sqlite_con: sqlite3.Connection, pg, table: str):
    columns = TABLE_COLUMNS[table]
    col_sql = sql.SQL(", ").join(map(qident, columns))
    placeholders = sql.SQL(", ").join([sql.Placeholder()] * len(columns))
    insert = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
        qident(table), col_sql, placeholders
    )

    rows = sqlite_con.execute(
        f'SELECT {", ".join(f""" "{c}" """ for c in columns)} FROM "{table}"'
    )

    count = 0
    with pg.cursor() as cur:
        for row in rows:
            values = [normalize_value(row[c]) for c in columns]
            cur.execute(insert, values)
            count += 1
    pg.commit()
    return count


def reset_identity_sequences(pg):
    # PostgreSQL identity sequences are automatically created. Set each sequence
    # to MAX(id), so the next generated ID is greater than all migrated IDs.
    for table in IDENTITY_TABLES:
        with pg.cursor() as cur:
            cur.execute(
                sql.SQL(
                    "SELECT setval(pg_get_serial_sequence(%s, %s), "
                    "COALESCE((SELECT MAX(id) FROM {}), 0), "
                    "CASE WHEN EXISTS (SELECT 1 FROM {}) "
                    "THEN true ELSE false END)"
                ).format(qident(table), qident(table)),
                (table, "id"),
            )
    pg.commit()


def get_pg_counts(pg) -> dict[str, int]:
    result = {}
    with pg.cursor() as cur:
        for table in TABLE_COLUMNS:
            cur.execute(
                sql.SQL("SELECT COUNT(*) FROM {}").format(qident(table))
            )
            result[table] = int(cur.fetchone()[0])
    return result


def get_pg_blob_totals(pg) -> dict[str, int]:
    result = {}
    with pg.cursor() as cur:
        for table, column in [
            ("known_embeddings", "embedding"),
            ("registered_face_embeddings", "embedding"),
        ]:
            cur.execute(
                sql.SQL(
                    "SELECT COALESCE(SUM(octet_length({})), 0) FROM {}"
                ).format(qident(column), qident(table))
            )
            result[table] = int(cur.fetchone()[0] or 0)
    return result


def hash_rows_sqlite(con: sqlite3.Connection, table: str) -> str:
    columns = TABLE_COLUMNS[table]
    order = ", ".join(f'"{c}"' for c in PRIMARY_KEYS[table])
    rows = con.execute(
        f'SELECT {", ".join(f""" "{c}" """ for c in columns)} '
        f'FROM "{table}" ORDER BY {order}'
    )

    h = hashlib.sha256()
    for row in rows:
        for c in columns:
            value = normalize_value(row[c])
            if value is None:
                h.update(b"<NULL>")
            elif isinstance(value, bytes):
                h.update(b"<BLOB>" + len(value).to_bytes(8, "big") + value)
            else:
                encoded = str(value).encode("utf-8")
                h.update(b"<VAL>" + len(encoded).to_bytes(8, "big") + encoded)
        h.update(b"<ROW>")
    return h.hexdigest()


def hash_rows_pg(pg, table: str) -> str:
    columns = TABLE_COLUMNS[table]
    order = sql.SQL(", ").join(map(qident, PRIMARY_KEYS[table]))
    query = sql.SQL("SELECT {} FROM {} ORDER BY {}").format(
        sql.SQL(", ").join(map(qident, columns)),
        qident(table),
        order,
    )

    h = hashlib.sha256()
    with pg.cursor() as cur:
        cur.execute(query)
        for row in cur.fetchall():
            for value in row:
                value = normalize_value(value)
                if value is None:
                    h.update(b"<NULL>")
                elif isinstance(value, bytes):
                    h.update(b"<BLOB>" + len(value).to_bytes(8, "big") + value)
                else:
                    encoded = str(value).encode("utf-8")
                    h.update(b"<VAL>" + len(encoded).to_bytes(8, "big") + encoded)
            h.update(b"<ROW>")
    return h.hexdigest()


def verify(sqlite_con: sqlite3.Connection, pg):
    sqlite_counts = get_sqlite_counts(sqlite_con)
    pg_counts = get_pg_counts(pg)

    print("\n=== ROW COUNT VERIFICATION ===")
    all_ok = True
    for table in TABLE_COLUMNS:
        ok = sqlite_counts[table] == pg_counts[table]
        all_ok &= ok
        print(
            f"{table:32} SQLite={sqlite_counts[table]:8} "
            f"PostgreSQL={pg_counts[table]:8} {'OK' if ok else 'MISMATCH'}"
        )

    sqlite_blobs = get_blob_totals(sqlite_con)
    pg_blobs = get_pg_blob_totals(pg)

    print("\n=== EMBEDDING BYTE VERIFICATION ===")
    for table in sqlite_blobs:
        ok = sqlite_blobs[table] == pg_blobs[table]
        all_ok &= ok
        print(
            f"{table:32} SQLite={sqlite_blobs[table]:10} "
            f"PostgreSQL={pg_blobs[table]:10} {'OK' if ok else 'MISMATCH'}"
        )

    print("\n=== EXACT DATA HASH VERIFICATION ===")
    for table in TABLE_COLUMNS:
        s_hash = hash_rows_sqlite(sqlite_con, table)
        p_hash = hash_rows_pg(pg, table)
        ok = s_hash == p_hash
        all_ok &= ok
        print(f"{table:32} {'OK' if ok else 'MISMATCH'}")
        if not ok:
            print(f"  SQLite:    {s_hash}")
            print(f"  PostgreSQL:{p_hash}")

    if not all_ok:
        raise RuntimeError(
            "\nMIGRATION VERIFICATION FAILED. "
            "Do not switch the VMS to PostgreSQL yet."
        )

    print("\nSUCCESS: SQLite and PostgreSQL data match.")


def main():
    args = get_args()
    sqlite_path = Path(args.sqlite).resolve()

    print("SQLite source :", sqlite_path)
    print("PostgreSQL    :", os.getenv("PGDATABASE"))
    print("PostgreSQL host:", os.getenv("PGHOST", "localhost"))
    print("PostgreSQL port:", os.getenv("PGPORT", "5432"))

    sqlite_con = sqlite_connect(sqlite_path)

    try:
        print("\nConnecting to PostgreSQL...")
        with pg_connect() as pg:
            print("Connected.")

            print("\nCreating PostgreSQL schema...")
            create_schema(pg)

            if args.truncate:
                print("Truncating target tables...")
                truncate_target(pg)

            print("\nMigrating tables...")
            # Parent first because fcm_device_tokens references auth_accounts.
            migration_order = [
                "auth_accounts",
                "detection_events",
                "detection_records",
                "known_embeddings",
                "registered_persons",
                "registered_face_embeddings",
                "fcm_device_tokens",
            ]

            for table in migration_order:
                count = copy_table(sqlite_con, pg, table)
                print(f"  {table}: {count} rows")

            print("\nResetting PostgreSQL identity sequences...")
            reset_identity_sequences(pg)

            verify(sqlite_con, pg)

            print("\nMigration completed successfully.")
            print("The SQLite file was not modified.")
            print("Image files were not moved or modified.")
            print("Image paths/URLs were copied as database values.")

    finally:
        sqlite_con.close()


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"\nERROR: {exc}", file=sys.stderr)
        sys.exit(1)
